alias lg="lazygit"
alias cdp="cd ~/projects/"
alias cdppn="cdpp && nvim"
alias cdppg="cdpp ~/projects/gli"
alias cdppgn="cdppg && nvim"
alias v="nvim"
alias v.="nvim ."
alias la="ls -a"
alias javav="sudo update-alternatives --config java"

